// Code generated by "stringer -type=Type"; DO NOT EDIT.

package hyperjson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeError-0]
	_ = x[TypeNull-1]
	_ = x[TypeObjectBegin-2]
	_ = x[TypeObjectEnd-3]
	_ = x[TypeArrayBegin-4]
	_ = x[TypeArrayEnd-5]
	_ = x[TypeBoolean-6]
	_ = x[TypeNumber-7]
	_ = x[TypeString-8]
	_ = x[typeWhitespace-9]
}

const _Type_name = "TypeErrorTypeNullTypeObjectBeginTypeObjectEndTypeArrayBeginTypeArrayEndTypeBooleanTypeNumberTypeStringtypeWhitespace"

var _Type_index = [...]uint8{0, 9, 17, 32, 45, 59, 71, 82, 92, 102, 116}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
