// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     Span.json
 */

package avro

import (
	"fmt"
	"io"
	"math"
)

type ByteWriter interface {
	Grow(int)
	WriteByte(byte) error
}

type StringWriter interface {
	WriteString(string) (int, error)
}

func encodeInt(w io.Writer, byteCount int, encoded uint64) error {
	var err error
	var bb []byte
	bw, ok := w.(ByteWriter)
	// To avoid reallocations, grow capacity to the largest possible size
	// for this integer
	if ok {
		bw.Grow(byteCount)
	} else {
		bb = make([]byte, 0, byteCount)
	}

	if encoded == 0 {
		if bw != nil {
			err = bw.WriteByte(0)
			if err != nil {
				return err
			}
		} else {
			bb = append(bb, byte(0))
		}
	} else {
		for encoded > 0 {
			b := byte(encoded & 127)
			encoded = encoded >> 7
			if !(encoded == 0) {
				b |= 128
			}
			if bw != nil {
				err = bw.WriteByte(b)
				if err != nil {
					return err
				}
			} else {
				bb = append(bb, b)
			}
		}
	}
	if bw == nil {
		_, err := w.Write(bb)
		return err
	}
	return nil

}

func readLong(r io.Reader) (int64, error) {
	var v uint64
	buf := make([]byte, 1)
	for shift := uint(0); ; shift += 7 {
		if _, err := io.ReadFull(r, buf); err != nil {
			return 0, err
		}
		b := buf[0]
		v |= uint64(b&127) << shift
		if b&128 == 0 {
			break
		}
	}
	datum := (int64(v>>1) ^ -int64(v&1))
	return datum, nil
}

func readMapString(r io.Reader) (map[string]string, error) {
	m := make(map[string]string)
	for {
		blkSize, err := readLong(r)
		if err != nil {
			return nil, err
		}
		if blkSize == 0 {
			break
		}
		if blkSize < 0 {
			blkSize = -blkSize
			_, err := readLong(r)
			if err != nil {
				return nil, err
			}
		}
		for i := int64(0); i < blkSize; i++ {
			key, err := readString(r)
			if err != nil {
				return nil, err
			}
			val, err := readString(r)
			if err != nil {
				return nil, err
			}
			m[key] = val
		}
	}
	return m, nil
}

func readSpan(r io.Reader) (*Span, error) {
	var str = &Span{}
	var err error
	str.Id, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.Trace, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.Parent, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.Name, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.Service, err = readString(r)
	if err != nil {
		return nil, err
	}
	str.TimestampInNanos, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.DurationInNanos, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.CsInNanos, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.CrInNanos, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.SsInNanos, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.SrInNanos, err = readLong(r)
	if err != nil {
		return nil, err
	}
	str.Tags, err = readMapString(r)
	if err != nil {
		return nil, err
	}

	return str, nil
}

func readString(r io.Reader) (string, error) {
	len, err := readLong(r)
	if err != nil {
		return "", err
	}

	// makeslice can fail depending on available memory.
	// We arbitrarily limit string size to sane default (~2.2GB).
	if len < 0 || len > math.MaxInt32 {
		return "", fmt.Errorf("string length out of range: %d", len)
	}

	if len == 0 {
		return "", nil
	}

	bb := make([]byte, len)
	_, err = io.ReadFull(r, bb)
	if err != nil {
		return "", err
	}
	return string(bb), nil
}

func writeLong(r int64, w io.Writer) error {
	downShift := uint64(63)
	encoded := uint64((r << 1) ^ (r >> downShift))
	const maxByteSize = 10
	return encodeInt(w, maxByteSize, encoded)
}

func writeMapString(r map[string]string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = writeString(k, w)
		if err != nil {
			return err
		}
		err = writeString(e, w)
		if err != nil {
			return err
		}
	}
	return writeLong(0, w)
}

func writeSpan(r *Span, w io.Writer) error {
	var err error
	err = writeLong(r.Id, w)
	if err != nil {
		return err
	}
	err = writeLong(r.Trace, w)
	if err != nil {
		return err
	}
	err = writeLong(r.Parent, w)
	if err != nil {
		return err
	}
	err = writeString(r.Name, w)
	if err != nil {
		return err
	}
	err = writeString(r.Service, w)
	if err != nil {
		return err
	}
	err = writeLong(r.TimestampInNanos, w)
	if err != nil {
		return err
	}
	err = writeLong(r.DurationInNanos, w)
	if err != nil {
		return err
	}
	err = writeLong(r.CsInNanos, w)
	if err != nil {
		return err
	}
	err = writeLong(r.CrInNanos, w)
	if err != nil {
		return err
	}
	err = writeLong(r.SsInNanos, w)
	if err != nil {
		return err
	}
	err = writeLong(r.SrInNanos, w)
	if err != nil {
		return err
	}
	err = writeMapString(r.Tags, w)
	if err != nil {
		return err
	}

	return nil
}

func writeString(r string, w io.Writer) error {
	err := writeLong(int64(len(r)), w)
	if err != nil {
		return err
	}
	if sw, ok := w.(StringWriter); ok {
		_, err = sw.WriteString(r)
	} else {
		_, err = w.Write([]byte(r))
	}
	return err
}
