// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     Span.json
 */

package avro

import (
	"io"
)

type Span struct {
	Id               int64
	Trace            int64
	Parent           int64
	Name             string
	Service          string
	TimestampInNanos int64
	DurationInNanos  int64
	CsInNanos        int64
	CrInNanos        int64
	SsInNanos        int64
	SrInNanos        int64
	Tags             map[string]string
}

func DeserializeSpan(r io.Reader) (*Span, error) {
	return readSpan(r)
}

func NewSpan() *Span {
	v := &Span{
		Tags: make(map[string]string),
	}

	return v
}

func (r *Span) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"trace\",\"type\":\"long\"},{\"name\":\"parent\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"service\",\"type\":\"string\"},{\"name\":\"timestampInNanos\",\"type\":\"long\"},{\"name\":\"durationInNanos\",\"type\":\"long\"},{\"name\":\"csInNanos\",\"type\":\"long\"},{\"name\":\"crInNanos\",\"type\":\"long\"},{\"name\":\"ssInNanos\",\"type\":\"long\"},{\"name\":\"srInNanos\",\"type\":\"long\"},{\"name\":\"tags\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}],\"name\":\"Span\",\"type\":\"record\"}"
}

func (r *Span) Serialize(w io.Writer) error {
	return writeSpan(r, w)
}
